# Generated by Django 3.1.7 on 2021-03-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todolist',
            new_name='TodolistModel',
        ),
    ]
