# Generated by Django 3.1.7 on 2021-03-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0002_auto_20210318_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodolistModel',
            new_name='Todolist',
        ),
    ]
